# Generated by Django 3.2.13 on 2024-06-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agriculture_info',
            fields=[
                ('name', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_id', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='', max_length=32)),
                ('device_location', models.CharField(default='', max_length=32)),
                ('device_state', models.BooleanField(default='')),
                ('device_creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_online', models.DateTimeField(default='', null=True)),
                ('agriculture_info', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to='api.agriculture_info')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('username', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=512)),
                ('email', models.EmailField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SensorMonitor_info',
            fields=[
                ('record_time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default='')),
                ('humidity', models.FloatField(default='')),
                ('co2', models.FloatField(default='')),
                ('luminance', models.FloatField(default='')),
                ('soi_humidity', models.FloatField(default='')),
                ('device_info', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_monitor_info', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('cycle', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('next_execution_date', models.DateField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='device_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_online', models.DateTimeField(null=True)),
                ('device_offline', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='在线时长（分钟）', null=True)),
                ('device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.device')),
            ],
        ),
        migrations.AddField(
            model_name='agriculture_info',
            name='user_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_infos', to='api.user_info'),
        ),
    ]
